Vps_solihullsfca
mssquaretech/PythonBatch6 pull request #23
Opened 2021-06-22 14:17 UTC by vikramps095

Vps_solihullsfca

Please Check and review

2021-06-22 15:49 UTC, mssquaretech requested changes
Please remove .idea folder, log.html, screenshots, output.xml, report.html files

2021-06-22 17:17 UTC, vikramps095 reviewed
Folder and File Deleted as suggested

2021-06-23 02:43 UTC, mssquaretech requested changes
Given statement missing in Feature file. Please make changes and update

2021-06-23 02:48 UTC, vikramps095 reviewed
Changes Done

2021-06-24 14:33 UTC, mssquaretech approved these changes

2021-06-24 14:35 UTC, mssquaretech commented
This PR is ready to merge.. @vikramps095 
@narendrashakya @Garima2412 @KaranNegi0405 @monalisha-90 . Can anyone of you review and approve to close this PR.
Thanks

2021-06-24 15:11 UTC, narendrashakya requested changes

2021-06-24 15:11 UTC, narendrashakya commented on Vikram/Resource/Pages/Solihullsfc_Homepage.robot
> +    sleep       2s
Please remove the hard sleep and instead add explicit wait.

2021-06-24 17:07 UTC, vikramps095 commented on Vikram/Resource/Pages/Solihullsfc_Homepage.robot
> +    sleep       2s
Changes Done. Thanks for Quick Review :)

2021-06-24 17:09 UTC, narendrashakya approved these changes
Approved.

2021-06-24 17:12 UTC, narendrashakya commented on Vikram/Resource/Pages/Solihullsfc_Homepage.robot
> +    sleep       2s
Thanks for quick changes.

2021-06-24 17:16 UTC, vikramps095 commented on Vikram/Resource/Pages/Solihullsfc_Homepage.robot
> +    sleep       2s
Thanks Again for quick reply

2021-06-24 17:16 UTC, vikramps095 commented on Vikram/Resource/Pages/Solihullsfc_Homepage.robot
> +    sleep       2s
Thanks once Again

2021-06-24 19:06 UTC, merged