Basavraj solihull
mssquaretech/PythonBatch6 pull request #25
Opened 2021-06-23 02:48 UTC by BasavrajR

Please review

2021-06-24 14:32 UTC, mssquaretech requested changes
This branch contains multiple folders like Configuration, Resource, Test etc.
Expected : only one folder should be there - BR_Solihullsfc.
Please remove other folders and add just one in root

2021-06-24 15:21 UTC, narendrashakya requested changes

2021-06-24 15:21 UTC, narendrashakya commented on Prateek.txt
> +Testing-BR
Branch having conflict with master. Please remove **Pratekk.txt** file.

2021-06-27 05:11 UTC, narendrashakya requested changes

2021-06-27 05:11 UTC, narendrashakya commented on Resource/Pages/SolihullPages.robot
> +             ${Lang1}             Should Contain    ${Lang}     C
Could you please check line 21 and update it accordinly.
This line of code matches all language and check if it contain 'C', here first language "Afrikaans" doesn't contain letter 'C'.
That's why script is failing.
Also, If you want to check letter 'C' contain in all language then If condition is required.

![image](https://user-images.githubusercontent.com/51281987/123533093-4ae73300-d730-11eb-8566-a7120ebee789.png)

2021-06-27 05:11 UTC, narendrashakya commented on Resource/Pages/SolihullPages.robot
> +                log to console    ${Lang1}
Could you please check on line 24 and update accordingly.
Here, Line 24 printing the ${Lang1} and this variable will store the boolean value from Line 21.
It will not store the language name which are starting with 'C'.

![image](https://user-images.githubusercontent.com/51281987/123533395-ce098880-d732-11eb-9348-cbe639c4886b.png)

2021-06-27 05:11 UTC, narendrashakya commented on Resource/Pages/SolihullPages.robot
> +             ${Lang}     get text       (//div[@class='option']/a)[${i}]
Could you please apply explicit wait in Line 20 till the element is visible. else it will get the blank space in ${Lang} variable.

![image](https://user-images.githubusercontent.com/51281987/123533419-0f019d00-d733-11eb-9807-93fd22fda10f.png)

2021-06-27 05:11 UTC, narendrashakya commented on Resource/Pages/SolihullPages.robot
> +             Run keyword if ${Lang1} == ${Lang}
Could you please apply correct indentation after 'If' keyword.
And also apply the "...         <2nd line>" after If keyword in 2nd line, else it will fail with saying 2 arugement is expected and got only 1.
![image](https://user-images.githubusercontent.com/51281987/123533543-0067b580-d734-11eb-8287-cc00c1b8e830.png)

![image](https://user-images.githubusercontent.com/51281987/123533480-abc43a80-d733-11eb-8657-70df69d359d1.png)

2021-06-27 05:12 UTC, narendrashakya commented on Prateek.txt
> +Testing-BR
Thanks, conflict file is removed as requested.

2021-06-27 15:40 UTC, BasavrajR reviewed
I made some change which is mentioned above comment

2021-06-27 15:40 UTC, BasavrajR commented on Resource/Pages/SolihullPages.robot
> +                log to console    ${Lang1}
I made same changes ..
 Created list which start with Letter C Language and try to click one by one.. in loop but getting issue. please suggest 

user search and click on Language selection dropdown
       set selenium implicit wait   5s
       Click Element                     ${Dropdwon}

       ${count}          get element count     ${Listxpath}


       FOR   ${i}   IN RANGE      1   ${count}

           wait until element is visible        (//div[@class='option']/a[contains(text(),'C')])[${i}]
           click element          (//div[@class='option']/a[contains(text(),'C')])[${i}]

           ${Lang}     get text       (//div[@class='option']/a[contains(text(),'C')])[${i}]

           log to console      ${Lang}
#           click element       ${Lang}
#           wait until element is visible        (//div[@class='option']/a[contains(text(),'C')])[${i}]


#           ELSE
#           Exit for loop
       END
--------------------------------------------------------------
Element '(//div[@class='option']/a[contains(text(),'C')])[3]' not visible after 5 seconds.

2021-06-29 15:19 UTC, BasavrajR reviewed
Please review new code updated.

2021-07-01 02:41 UTC, mssquaretech approved these changes
Approving changes..

2021-07-02 11:17 UTC, narendrashakya approved these changes

2021-07-04 05:43 UTC, merged