Assignment Solihullsfc robotframework
mssquaretech/PythonBatch6 pull request #26
Opened 2021-06-23 16:27 UTC by Garima2412

Please review and provide feedback

2021-06-24 06:37 UTC, narendrashakya requested changes

2021-06-24 06:37 UTC, narendrashakya commented on Garima_Solihullsfc/Resource/Pages/HomePage.robot
> +        log to console                                  ${PageTitle}
It only printing the "English" Title on each iteration. Need to impliment wait and print the title.
**Title getting print on each Title :** Solihull Sixth Form College: Post 16 education, A Levels and BTECs — Solihull Sixth Form College

![image](https://user-images.githubusercontent.com/51281987/123214240-960d0600-d4e4-11eb-81f4-2aaddf93c357.png)

2021-06-24 06:40 UTC, narendrashakya requested changes
"Test" folder is not present

2021-06-24 06:40 UTC, narendrashakya commented on Garima_Solihullsfc/solihullsfc.robot
> +*** Settings ***
**Test** directory is not present, feature file need to be present in Test Directory.

2021-06-24 08:50 UTC, Garima2412 commented on Garima_Solihullsfc/Resource/Pages/HomePage.robot
> +        log to console                                  ${PageTitle}
Updated

2021-06-24 08:53 UTC, Garima2412 commented on Garima_Solihullsfc/Resource/Pages/HomePage.robot
> +        log to console                                  ${PageTitle}
Updated - working now 
![result](https://user-images.githubusercontent.com/79889760/123233367-a24e8e80-d4f7-11eb-91d7-cadaae7e37c5.JPG)

2021-06-24 10:21 UTC, narendrashakya requested changes
Please update the correct path under ENV robot file.

2021-06-24 10:21 UTC, narendrashakya commented on Configuration/Env.robot
> +Resource                    ../Pages/Adhoc.robot
Adhoc robot file is under **Resource** directory, resource path missing this directory. It giving below error.

Garima_Solihullsfc\Configuration\Env.robot' on line 3: Resource file '..\Pages\Adhoc.robot' does not exist.
**Correct path will be :** ../Resource/Pages/Adhoc.robot

2021-06-24 13:06 UTC, narendrashakya approved these changes
Approved 👍🏼

2021-06-24 14:25 UTC, mssquaretech commented on Garima_Solihullsfc/Resource/Pages/HomePage.robot
> +        log to console                                  ${PageTitle}
Wow.. keep it up

2021-06-24 14:30 UTC, mssquaretech requested changes
This branch contains multiple folders like Configuration, Resource, Test and Garima_Solihullsfc.
Expected : only one folder should be there - Garima_Solihullsfc.
Please remove other folders. 
Rest all is fine

2021-06-25 02:56 UTC, mssquaretech approved these changes

2021-06-25 02:57 UTC, mssquaretech reviewed
Changes done.. ready to merge

2021-06-25 02:57 UTC, merged