Monalisha_SoliHull Assignment
mssquaretech/PythonBatch6 pull request #29
Opened 2021-06-25 12:21 UTC by monalisha-90

This is the assignment for SoliHull using Robot framework
Please review and approve.

2021-06-26 17:17 UTC, Garima2412 commented on Monalisha/Resources/Pages/SoliHull_page.robot
> +
Kindly remove Unused spaces

2021-06-26 17:17 UTC, Garima2412 commented on Monalisha/Resources/Solihull_SD.robot
> +
Kindly remove extra spaces

2021-06-26 17:17 UTC, Garima2412 commented on Monalisha/Resources/Pages/SoliHull_page.robot
> +        Exit For Loop if            ${i}==${SelectedLangCount}
We can omit the if condition here,
Exit for loop condition is not required as the loop is working perfectly with in the apt range calculated above.

2021-06-27 05:17 UTC, narendrashakya requested changes, later dismissed
Could you Please remove other member folder from the branch. Only your name folder is required.
Rest is good to merge. Thanks.

![image](https://user-images.githubusercontent.com/51281987/123533683-fbefcc80-d734-11eb-91c9-ac8e180d120d.png)

2021-06-28 02:43 UTC, mssquaretech approved these changes
Ok to Approve

2021-06-28 02:58 UTC, monalisha-90 commented on Monalisha/Resources/Pages/SoliHull_page.robot
> +
@Garima2412 : update the expected changes. Please review and approve.
Thanks.

2021-06-28 02:58 UTC, monalisha-90 commented on Monalisha/Resources/Solihull_SD.robot
> +
@Garima2412 : updated expected changes. Please review and approve.
thanks

2021-06-28 03:00 UTC, narendrashakya approved these changes
Good to merge.

2021-06-28 03:00 UTC, merged